config/routes.rb
Rails.application.routes.draw do
  root 'calculadora#index'   # Define la ruta principal
  post 'calcular', to: 'calculadora#calcular'  # Define la ruta para el cálculo
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def index
  end
end

app/controllers/calculadora_controller.rb
class CalculadoraController < ApplicationController
    def index
      render 'articles/index'
    end
  
    def calcular
      numero1 = params[:numero1].to_f
      numero2 = params[:numero2].to_f
      operacion = params[:operacion]
  
      @resultado = case operacion
                   when "suma"
                     numero1 + numero2
                   when "resta"
                     numero1 - numero2
                   end
  
      render 'articles/index', status: :see_other
    end
  end
  

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/index.html.erb
<h1>Calculadora de Suma y Resta</h1>

<%= form_with url: calcular_path, method: :post, local: true, data: { turbo: false } do |form| %>
  <div>
    <label for="numero1">Número 1:</label>
    <%= form.number_field :numero1 %>
  </div>
  <div>
    <label for="numero2">Número 2:</label>
    <%= form.number_field :numero2 %>
  </div>
  <div>
    <%= form.radio_button :operacion, 'suma' %> Suma
    <%= form.radio_button :operacion, 'resta' %> Resta
  </div>
  <div>
    <%= form.submit 'Calcular' %>
  </div>
<% end %>

<div>
  <h2>Resultado:</h2>
  <p id="resultado"><%= @resultado %></p>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Aplicacion1" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>